@startuml
'https://plantuml.com/sequence-diagram

autonumber

Alice -> Controller: Authentication Request
Controller --> Bob: Authentication Response

Controller <-- Bob: another authentication Response
Alice <-- Controller: another authentication Response
@enduml